apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2019-07-31T18:24:13Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: docker-desktop
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  name: docker-desktop
  resourceVersion: "3511"
  selfLink: /api/v1/nodes/docker-desktop
  uid: 6618072e-b3c0-11e9-b937-025000000001
spec: {}
status:
  addresses:
  - address: 192.168.65.3
    type: InternalIP
  - address: docker-desktop
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "56453061334"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8062420Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 61255492Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8164820Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2019-08-01T08:04:42Z"
    lastTransitionTime: "2019-07-31T18:24:10Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2019-08-01T08:04:42Z"
    lastTransitionTime: "2019-07-31T18:24:10Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2019-08-01T08:04:42Z"
    lastTransitionTime: "2019-07-31T18:24:10Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2019-08-01T08:04:42Z"
    lastTransitionTime: "2019-07-31T18:24:10Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - jupyter/pyspark-notebook@sha256:a52488dbb2587531cafbd7c28e2aede15f9046aa7261337df9c8ba3ba8e058c2
    - jupyter/pyspark-notebook:latest
    sizeBytes: 4494834872
  - names:
    - arthur:miniconda
    sizeBytes: 3183728367
  - names:
    - basfbds/ubuntu-miniconda3@sha256:c5711a899d7e3fc2cd0ff65e7ba586201b6a77226b0897522c7548932b91c0f0
    - basfbds/ubuntu-miniconda3:18.04
    sizeBytes: 498709907
  - names:
    - k8s.gcr.io/etcd@sha256:17da501f5d2a675be46040422a27b7cc21b8a43895ac998b171db1c346f361f7
    - k8s.gcr.io/etcd:3.3.10
    sizeBytes: 258116302
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:e29561119a52adad9edc72bfe0e7fcab308501313b09bf99df4a9638ee634989
    - k8s.gcr.io/kube-apiserver:v1.14.3
    sizeBytes: 209941374
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:d8dafc4f365d5c5912a48ab54b0cdc75ce16d91c93b62491328f3a26160dfa42
    - k8s.gcr.io/kube-controller-manager:v1.14.3
    sizeBytes: 157958206
  - names:
    - k8s.gcr.io/kube-proxy@sha256:d51258f104b6efdf9a6d739eb1b9453a157fa349f04e1279ece5a8cd277140aa
    - k8s.gcr.io/kube-proxy:v1.14.3
    sizeBytes: 82106236
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:de46560aa956cafb23eb0b6cc48926bc6ff24e337ce3fef6a4895a2ea120c30d
    - k8s.gcr.io/kube-scheduler:v1.14.3
    sizeBytes: 81579742
  - names:
    - docker/kube-compose-api-server@sha256:035e674c761c8a9bffe25a4f7c552e617869d1c1bfb2f84074c3ee63f3018da4
    - docker/kube-compose-api-server:v0.4.23
    sizeBytes: 49939182
  - names:
    - k8s.gcr.io/coredns@sha256:02382353821b12c21b062c59184e227e001079bb13ebd01f9d3270ba0fcbf1e4
    - k8s.gcr.io/coredns:1.3.1
    sizeBytes: 40303560
  - names:
    - docker/kube-compose-controller@sha256:e15dad3aa71c0051e64831b145680f76f261f433bc6fc49987c45e43e039960b
    - docker/kube-compose-controller:v0.4.23
    sizeBytes: 35271598
  - names:
    - k8s.gcr.io/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea
    - k8s.gcr.io/pause:3.1
    sizeBytes: 742472
  nodeInfo:
    architecture: amd64
    bootID: a7be67a6-2699-4c6c-a03d-00015f8835a2
    containerRuntimeVersion: docker://19.3.1
    kernelVersion: 4.9.184-linuxkit
    kubeProxyVersion: v1.14.3
    kubeletVersion: v1.14.3
    machineID: 4e4dce3b-af94-48e2-b443-97ebefc2d5ff
    operatingSystem: linux
    osImage: Docker Desktop
    systemUUID: B47045C7-0000-0000-88C7-503DF4D9AE1D
